sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 13306
    database: sky_take_out
    username: root
    password: 151486
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXbulGTUzy6Pd7
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    password: ''
    database: 10