sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 13306
    database: sky_take_out
    username: root
    password: 151486
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXbulGTUzy6Pd7
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    password: ''
    database: 10
  wechat:
    appid: wxea8c9fa75115b2e5
    secret: 3f7f69163705663e0fcf4933c9f61ed4
    mchid:
    mch-serial-no:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url: https://62a36f9e.r28.cpolar.top/notify/paySuccess
    refund-notify-url: https://62a36f9e.r28.cpolar.top/notify/refundSuccess